# CT4101 - Milestone 2
## 1 dataset loading and exploration
This project will explore whether patient demographics, behaviours and history can predict a positive cervical cancer result using the UCI Cervical Cancer (Risk Factors) dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# load the dataset
df = pd.read_csv(
    "../data/risk_factors_cervical_cancer.csv",
    na_values=["?"]
)

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (858, 36)

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0

## 2 - data audit 
## 2.1 data types and any missing values
I am going to examine the dataset for missing values and variables before determining which is the best pre-processing method for this

In [3]:
# check data types
print("Data types:")
print(df.dtypes.value_counts())

# count missing values per column
missing_values = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing Percentage": (df.isna().mean() * 100).round(2)
})

# display columns containing missing values
display(
    missing_values[missing_values["Missing Count"] > 0]
    .sort_values("Missing Percentage", ascending=False)
)

Data types:
float64    26
int64      10
Name: count, dtype: int64

                                    Missing Count  Missing Percentage
STDs: Time since first diagnosis              787               91.72
STDs: Time since last diagnosis               787               91.72
IUD (years)                                   117               13.64
IUD                                           117               13.64
Hormonal Contraceptives                       108               12.59
Hormonal Contraceptives (years)               108               12.59
STDs (number)                                 105               12.24
STDs                                          105               12.24
STDs:vulvo-perineal condylomatosis            105               12.24
STDs:vaginal condylomatosis                   105               12.24
STDs:pelvic inflammatory disease              105               12.24
STDs:syphilis                                 105               12.24
STDs:genital herpes                           105               12.24
STDs:molluscum contagiosum                    105               12.24
STDs:HIV                                      105               12.24
STDs:AIDS                                     105               12.24
STDs:condylomatosis                           105               12.24
STDs:cervical condylomatosis                  105               12.24
STDs:HPV                                      105               12.24
STDs:Hepatitis B                              105               12.24
Num of pregnancies                             56                6.53
Number of sexual partners                      26                3.03
Smokes (packs/year)                            13                1.52
Smokes (years)                                 13                1.52
Smokes                                         13                1.52
First sexual intercourse                        7                0.82